# # possible values : production, development
# app_mode: development

server:
  # Protocol (http or https)
  protocol: http
  ip: 192.168.0.100
  port: 8080
  # Redirect to correct domain if host header does not match domain
  enforce_domain: true
  log_path: "./logger/ginchat/"
  # HTTP log output stdout
  log_stdout: false
  # file upload path
  attach_path: "./mnt"
  # server debug
  debug: false
  nodes:
    - "192.168.0.100"
    - "10.211.55.3"
rpc:
  port: 8090

mysql:
  ip: 127.0.0.1
  port: 3306
  user: root
  pwd: root
  db_name: chat
  show_sql: true
  max_open_conns : 2
redis:
  ip: 10.211.55.3
  port: 6666